version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: finova-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: dev-file
      KC_HTTP_PORT: 8080
    ports:
      - "9080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    networks:
      - finova-network

networks:
  finova-network:
    driver: bridge
