server:
  port: 8083

spring:
  application:
    name: planning-service
  datasource:
    url: jdbc:h2:mem:planning_service_db
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  # Spring Security OAuth 2.0 Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          # Configure your OAuth 2.0 provider URLs when OAuth is enabled
          # Example for Keycloak:
          # issuer-uri: http://localhost:8080/auth/realms/finova
          # jwk-set-uri: http://localhost:8080/auth/realms/finova/protocol/openid-connect/certs
          
          # Example for Auth0:
          # issuer-uri: https://your-domain.auth0.com/
          # jwk-set-uri: https://your-domain.auth0.com/.well-known/jwks.json
          
          # Example for Azure AD:
          # issuer-uri: https://sts.windows.net/{tenant-id}/
          # jwk-set-uri: https://login.microsoftonline.com/{tenant-id}/discovery/v2.0/keys
          
          # Keycloak configuration for demo
          issuer-uri: http://localhost:9080/realms/finova
          jwk-set-uri: http://localhost:9080/realms/finova/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      account-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Finova Configuration
finova:
  # Planning Service Configuration
  planning:
    default-inflation-rate: 0.03
    default-investment-return: 0.07
    default-retirement-duration: 25
    social-security:
      full-retirement-age: 67
      early-retirement-age: 62
      delayed-retirement-age: 70
  # Security Configuration
  security:
    # Set to true when you have OAuth 2.0 provider configured
    oauth:
      enabled: true  # SSO ENABLED - Keycloak configuration
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:8000,http://localhost:8080,http://localhost:4200,https://*.finova.com"
    public-paths:
      - /actuator/**
      - /api/planning/health
      - /api/auth/health
      - /error
      - /h2-console/**
    jwt:
      clock-skew: 60  # seconds
      cache-duration: 300  # seconds

logging:
  level:
    com.finova.planning: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.cors: DEBUG
