server:
  port: 8085

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:password@localhost:27017/analytics_db?authSource=admin}
      auto-index-creation: true
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.finova.analytics: DEBUG
    org.springframework.data.mongodb: DEBUG

